### ISSUE TITLE
wasmtime_config_interruptable_set missing

### ISSUE THREAD

**Issue by redthing1** [bytecodealliance/wasmtime-dotnet#117]
```
System.EntryPointNotFoundException: Unable to find an entry point named 'wasmtime_config_interruptable_set' in shared library 'wasmtime'.
   at Wasmtime.Config.Native.wasmtime_config_interruptable_set(Handle config, Boolean enable)
   at Wasmtime.Config.WithInterruptability(Boolean enable)

```

**Comment by redthing1** [comment]
https://github.com/bytecodealliance/wasmtime/commit/c22033bf9397e9bec3704ff10ca897598e3dcd08
