### ISSUE TITLE
Cross-Engine Instantation

### ISSUE THREAD

**Issue by christophwille** [bytecodealliance/wasmtime-dotnet#32]
I finally got around to updating to the latest version, this was fairly smooth. For fun I tried the following:

https://github.com/christophwille/csharp-opa-wasm/blob/master/src/Opa.Wasm/OpaModule.cs#L19

Basically, using one Engine to load the module, a new Engine to run it - and that bombed:

```
Wasmtime.WasmtimeException
  HResult=0x80131500
  Message=cross-`Engine` instantiation is not currently supported
  Source=Wasmtime.Dotnet
  StackTrace:
   at Wasmtime.Instance..ctor(LinkerHandle linker, Module module)
   at Wasmtime.Host.Instantiate(Module module)
   at Opa.Wasm.OpaPolicy.Initialize(Module module) in D:\GitWorkspace\csharp-opa-wasm\src\Opa.Wasm\OpaPolicy.cs:line 104
   at Opa.Wasm.OpaPolicy..ctor(OpaModule module, Module wasmModule) in D:\GitWorkspace\csharp-opa-wasm\src\Opa.Wasm\OpaPolicy.cs:line 24
   at Opa.Wasm.ConsoleSample.Program.EvaluateHelloWorld() in D:\GitWorkspace\csharp-opa-wasm\src\Opa.Wasm.ConsoleSample\Program.cs:line 40
   at Opa.Wasm.ConsoleSample.Program.Main(String[] args) in D:\GitWorkspace\csharp-opa-wasm\src\Opa.Wasm.ConsoleSample\Program.cs:line 13
```

As you remember, I do the "precompilation" to save time on run. Is it actually safe to use the Engine concurrently?

**Comment by yurydelendik** [comment]
> Is it actually safe to use the Engine concurrently?

At wasmtime level, Engine is designed to be thread safe. Looking as wasmtime-dotnet, it appears to be true as well.

It is rare you will need multiple engines. Maybe to create completely independent containers within single process, but it appears be to not your use case. Is there a reason to maintain different Engine and Store, and still allow code, instantiated in different stores, to communicate between each other?

**Comment by christophwille** [comment]
If Engine is designed to be thread-safe, that works fine for me. It was out of interest and a bit how I might be designing my APIs (I defered doing the APIs as long as stuff moves around in wasmtime).
