### ISSUE TITLE
Config.WithCompilerStrategy() throws System.ArgumentException

### ISSUE THREAD

**Issue by matt9ucci** [bytecodealliance/wasmtime-dotnet#72]
When running the code:

```csharp
class Program
{
    static void Main(string[] args)
    {
        var config = new Wasmtime.Config().WithCompilerStrategy(Wasmtime.CompilerStrategy.Cranelift);
    }
}
```

Result:

```
Unhandled exception. System.ArgumentException: Enum underlying type and the object must be same type
or object must be a String. Type passed in was 'System.Byte'; the enum underlying type was 'System.Int32'.
   at System.RuntimeType.IsEnumDefined(Object value)
   at System.Enum.IsDefined(Type enumType, Object value)
   at Wasmtime.Config.WithCompilerStrategy(CompilerStrategy strategy)
   at Program.Main(String[] args) in C:\XXXX\Program.cs:line 5
```

- wasmtime-dotnet: 0.29.0-preview1
- `dotnet --version`: 5.0.205

**Comment by peterhuene** [comment]
Hi @matt9ucci.  Thanks for the report! I've found a few other bugs relating to this in `Config` that I'll push the fixes up soon.

**Comment by peterhuene** [comment]
Hi @matt9ucci.  The fix is now in `main` and should be in the next release of the package (TBD).
