### ISSUE TITLE
Calling function with string arguments returns out of bounds memory error.

### ISSUE THREAD

**Issue by JamieSinn** [bytecodealliance/wasmtime-dotnet#97]

**Comment by JamieSinn** [comment]
Managed to get a slightly different error:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/c-api/src/linker.rs:105:80
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: wiggle::run_in_dummy_executor
   5: std::panicking::try
   6: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1,A2,A3,A4),R>>::into_func::wasm_to_host_shim
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: _wasmtime_setjmp
  14: wasmtime_runtime::traphandlers::catch_traps
  15: wasmtime::func::Func::call_impl
  16: _wasmtime_func_call
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Unhandled exception. Wasmtime.TrapException: called `Option::unwrap()` on a `None` value
   at Wasmtime.Function.Invoke(StoreContext context, ReadOnlySpan`1 arguments)
   at Wasmtime.Function.Invoke(IStore store, Object[] arguments)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Example.Program.runWASM() in /Users/jamiesinn/git/dotnet-server-sdk/Example/Program.cs:line 76
   at Example.Program.Main(String[] args) in /Users/jamiesinn/git/dotnet-server-sdk/Example/Program.cs:line 12
   at Example.Program.<Main>(String[] args)

```

**Comment by peterhuene** [comment]
Hi @JamieSinn.

The first error seems to be due to where you've written the strings to. You declare a `Memory` to write the data to, but that memory doesn't appear to be imported to the instance and thus the pointers you're passing the guest program aren't valid for the memory its accessing internally.

I suspect you want to get the exported memory from the instance to write the data to rather than using a host `Memory` object. The commented out line `var memory = instance.GetMemory(store, "memory");` would do it (assuming the memory is exported); that's the memory the strings should be written to.

The second error comes from a line having to do with defining WASI in the instance. Did you change the code to call `Linker.DefineWasi`? If so, you'll need to also do a `Store.SetWasiConfiguration` call prior to instantiation.

Regarding your definition of the host function `env.abort`, you will likely want to use a `Caller` parameter to access the caller's memory rather than creating another instance and getting its exported memory.

It would look like this:

```c#
linker.Define(
    "env",
    "abort",
    Function.FromCallback(store, (Caller caller, int message, int filename, int linenum, int colnum) =>
    {
        var mem = caller.GetMemory("memory");

        ...
    })
);
```

I find it odd that they would pass you the line and column numbers as pointers to a string representation of those numbers, but I don't know much about assemblyscript. The hardcoded lengths are also a little scary (they must be communicating the string lengths somehow).

Let me know if any of the above helps.

**Comment by JamieSinn** [comment]
Hey Peter, appreciate the deep dive. 

Let me give some more context: 
ASC gives the `env:abort` function signature - hence the override. 

More info here: (https://www.assemblyscript.org/debugging.html#overriding-abort) 
The fixed 1000 length strings is because of how we have to parse until the next "real" null terminated string, we don't know how long this is. It's a very hacky hack.
 
 
The first workaround we had to do - is that the built in functions to read/write strings from memory are based on UTF8, while the asc/WASM architecture is to use UTF16, which I had to hackily parse out by skipping the zero'd second byte. 

```
        static string To64BitString(string input)
        {
            var sb = new StringBuilder();
            foreach (var t in input)
            {
                sb.Append(t);
                sb.Append("\0");
            }

            return sb.ToString();
        }

        static string From64Bitstring(string input)
        {
            var asciiBytes = Encoding.ASCII.GetBytes(input);
            if (asciiBytes[1] != 0) return input;
            var actualErrorMessage = new StringBuilder();

            foreach (var asciiByte in asciiBytes)
            {
                Console.WriteLine("UTF16/64Bit dumbness: {0}, {1}", asciiByte, (char) asciiByte);
            }

            for (var i = 0; i < asciiBytes.Length; i += 2)
            {
                if (asciiBytes[i] == 0) break;

                actualErrorMessage.Append((char) asciiBytes[i]);
            }

            return actualErrorMessage.ToString();
        }
```


For the raw source code from the JS guest code - we're just parsing the JSON and then returning it. Nothing special.
```
export function generateBucketedConfig(configStr: string, userStr: string) : string  {

    const config: JSON.Obj = <JSON.Obj>(JSON.parse(configStr))
    const user: JSON.Obj = <JSON.Obj>(JSON.parse(userStr))

    const bucketedConfig = new BucketedUserConfig(config)

    return bucketedConfig.stringify()
}
```

From the same ASC built WASM file - we can read/write memory fine and call the function (minus it not understanding the i32 return type of a pointer) by using WASMER/Golang.

The memory address of 10000 and 12000 should be (imo) outside the "needed" area to run the actual WASM - but if i'm too low I can bump this up higher and try running that with a second or third page address.

**Comment by JamieSinn** [comment]
Full output from the current way i'm dumping data out:
```
Config data: "project":{"_id":"_project"},"environment":{"_id":"environment"}}
User data: {"user_id":"test_id"}
123
Cannot parse JSON
~lib/assemblyscript-json/decoder.ts
618475290624
4323455642275676160
Unhandled exception. Wasmtime.TrapException: wasm trap: wasm `unreachable` instruction executed
wasm backtrace:
    0: 0x4e9a - <unknown>!~lib/assemblyscript-json/decoder/JSONDecoder<~lib/assemblyscript-json/JSON/Handler>#deserialize
    1: 0x4f48 - <unknown>!~lib/assemblyscript-json/JSON/_JSON.parse<~lib/string/String>
    2: 0x3716 - <unknown>!src/index/generateBucketedConfig
    3: 0x6565 - <unknown>!export:src/index/generateBucketedConfig

   at Wasmtime.Function.Invoke(StoreContext context, ReadOnlySpan`1 arguments)
   at Wasmtime.Function.Invoke(IStore store, Object[] arguments)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Example.Program.runWASM() in /Users/jamiesinn/git/dotnet-server-sdk/Example/Program.cs:line 95
   at Example.Program.Main(String[] args) in /Users/jamiesinn/git/dotnet-server-sdk/Example/Program.cs:line 12
   at Example.Program.<Main>(String[] args)
```

and the C# Source: 
```
 static void runWASM()
        {
            using var engine = new Engine();
            using var module = Module.FromFile(engine,
                "/Users/jamiesinn/git/js-sdks/lib/shared/bucketing-assembly-script/build/bucketing-lib-debug.wasm");
            using var linker = new Linker(engine);
            using var store = new Store(engine);
            linker.DefineWasi();
            linker.Define(
                "env",
                "abort",
                Function.FromCallback(store, (int message, int filename, int linenum, int colnum) =>
                {
                    var inst = linker.Instantiate(store, module);
                    var mem = inst.GetMemory(store, "memory");

                    // WASM - You suck. 64 bit/ UTF16 encoded strings.
                    var messageStr = From64Bitstring(mem.ReadString(store, message, 100));
                    var filenameStr = From64Bitstring(mem.ReadString(store, filename, 100));
                    var lineNumStr = mem.ReadIntPtr(store, linenum);
                    var colNumStr = mem.ReadIntPtr(store, colnum);
                    Console.WriteLine(messageStr);
                    Console.WriteLine(filenameStr);
                    Console.WriteLine(lineNumStr);
                    Console.WriteLine(colNumStr);
                })
            );
            //var memory = new Memory(store, 10);
            //linker.Define("env", "memory", memory);


            var instance = linker.Instantiate(store, module);
            var memory = instance.GetMemory(store, "memory");
            memory.Grow(store, 10);

            var config =
                To64BitString("{\"project\":{\"_id\":\"_project\"},\"environment\":{\"_id\":\"environment\"}}\0");
            var user = To64BitString("{\"user_id\":\"test_id\"}");

            var configaddr = 70000;

            var useraddr = 72000;

            for (var i = 0; i < config.Length; i++)
            {
                memory.GetSpan(store)[configaddr + i] = (byte) config[i];
            }

            for (var i = 0; i < user.Length; i++)
            {
                memory.GetSpan(store)[(useraddr + i)] = (byte) user[i];
            }

            //var configBytesWritten = memory?.WriteString(store, configaddr, config);
            //var useraddr = configaddr + configBytesWritten!;
            //var userBytesWritten = memory?.WriteString(store, (int) configaddr+config.Length + 1, user);


            dynamic generateBucketedConfig = instance.GetFunction(store, "generateBucketedConfig")!;


            // if (configBytesWritten == null || userBytesWritten == null)
            // {
            //     Console.Out.WriteLine("Failed to write to memory.");
            //     return;
            // }

            var config2 = memory.ReadString(store, configaddr + 1, (int) config.Length);
            var user2 = memory.ReadString(store, useraddr, (int) user.Length );


            Console.Out.WriteLine("Config data: " + config2);
            Console.Out.WriteLine("User data: " + user2);
            var span = memory.GetSpan(store);
            Console.WriteLine(span.ToArray()[useraddr]);
            var result = generateBucketedConfig?.Invoke(store, configaddr, (int) configaddr + config.Length + 1);

            Console.WriteLine("generateBucketedConfig result: " + result);
        }
```


Looks like this might be an ASC issue at the root? Not immensely clear on that.

**Comment by peterhuene** [comment]
Looking at the top frame from the original out-of-bounds memory access, it appears to be from [String.UTF8.byteLength](https://github.com/AssemblyScript/assemblyscript/blob/main/std/assembly/string.ts#L671-L672), where I've highlighted the interesting lines.

This appears to be looking for a [common header](https://www.assemblyscript.org/memory.html#string-layout) that precedes the string address by 20 bytes. 

Looking at the [header definition](https://www.assemblyscript.org/memory.html#common-header-layout), I don't think you'll be able to synthesize legal values for these fields as they appear to be internal to AssemblyScript's GC.

I still suspect that there must be some interop functionality provided by AssemblyScript to enable hosts can allocate strings to pass AssemblyScript guest programs.

**Comment by peterhuene** [comment]
See [this section on the garbage collector](https://www.assemblyscript.org/garbage-collection.html#garbage-collection) in AssemblyScript and how to interact with it from a host program.

It links to [using the loader](https://www.assemblyscript.org/loader.html#using-the-loader) which defines wrapper functions specifically for allocating new strings.

**Comment by JamieSinn** [comment]
So those wrapper functions are only valid for using it in JS (ie using asc to read from a guest in JS.) The built WAT file does not include any exports for `__newString`
```
 (export "__new" (func $~lib/rt/itcms/__new))
 (export "__pin" (func $~lib/rt/itcms/__pin))
 (export "__unpin" (func $~lib/rt/itcms/__unpin))
 (export "__collect" (func $~lib/rt/itcms/__collect))
 (export "__rtti_base" (global $~lib/rt/__rtti_base))
 (export "memory" (memory $0))
 (export "generateBucketedConfig" (func $export:src/index/generateBucketedConfig))
 ```
 
 This generally seems like there's an XKCD problem of agreeing standards between various libraries/tools.

**Comment by JamieSinn** [comment]
No handy global export for Id's unfortunately.

Using the `__new` func to allocate + get addresses:

```
private static void runWASM()
        {
            using var engine = new Engine();
            using var module = Module.FromFile(engine,
                "/Users/jamiesinn/git/js-sdks/lib/shared/bucketing-assembly-script/build/bucketing-lib-debug.wasm");
            using var linker = new Linker(engine);
            using var store = new Store(engine);
            linker.DefineWasi();
            linker.Define(
                "env",
                "abort",
                Function.FromCallback(store, (int message, int filename, int linenum, int colnum) =>
                {
                    var inst = linker.Instantiate(store, module);
                    var mem = inst.GetMemory(store, "memory");

                    // WASM - You suck. 64 bit/ UTF16 encoded strings.
                    var messageStr = From64Bitstring(mem.ReadString(store, message, 100));
                    var filenameStr = From64Bitstring(mem.ReadString(store, filename, 100));
                    var lineNumStr = mem.ReadIntPtr(store, linenum);
                    var colNumStr = mem.ReadIntPtr(store, colnum);
                    Console.WriteLine(messageStr);
                    Console.WriteLine(filenameStr);
                    Console.WriteLine(lineNumStr);
                    Console.WriteLine(colNumStr);
                })
            );
            //var memory = new Memory(store, 10);
            //linker.Define("env", "memory", memory);
            const string config = "{\"project\":{\"_id\":\"_project\"},\"environment\":{\"_id\":\"environment\"}}";
            const string user = "{\"user_id\":\"test_id\"}";

            var instance = linker.Instantiate(store, module);
            var memory = instance.GetMemory(store, "memory");

            dynamic __new = instance.GetFunction(store, "__new")!;
            var configAddress = __new?.Invoke(store, Encoding.Unicode.GetBytes(config).Length, (uint)1);
            var userAddress = __new?.Invoke(store, Encoding.Unicode.GetBytes(user).Length, (uint)1);
            
            Encoding.Unicode.GetBytes(config, memory?.GetSpan(store).Slice(configAddress));          
            Encoding.Unicode.GetBytes(config, memory?.GetSpan(store).Slice(userAddress));
            
            
            for (var i = 0; i <  Encoding.Unicode.GetBytes(config).Length; i++)
            {
                Console.Write((char)memory.GetSpan(store)[(configAddress + i)]);
            }
            Console.WriteLine();
            

            dynamic generateBucketedConfig = instance.GetFunction(store, "generateBucketedConfig")!;
            
            var result = generateBucketedConfig?.Invoke(store, configAddress, userAddress);

            Console.WriteLine("generateBucketedConfig result: " + result);
        }
```

fails with a root System error:
```
Unhandled exception. System.TypeLoadException: The generic type 'System.Func`4' was used with an invalid instantiation in assembly 'System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   at Example.Program.runWASM()
   at Example.Program.Main(String[] args) in /Users/jamiesinn/git/dotnet-server-sdk/Example/Program.cs:line 12
```
Line 12 is the call to runWASM.

I can provide the WAT and WASM files privately for better debugging on your end - let me know if that would help.

**Comment by peterhuene** [comment]
It's probably more efficient to call `Encoding.Unicode.GetByteCount` rather than `GetBytes(...).Length`.

If you want to shoot me the .wasm file at the email address on my github profile, I can take a quick look and see what's going wrong.

**Comment by peterhuene** [comment]
With this C# program and your wasm in the project directory:

```c#

using System.Text;
using Wasmtime;

String ReadAssemblyScriptString(IStore store, Memory memory, int address)
{
    // The length of the string is at offset -4 in AssemblyScript string layout.
    var length = memory.ReadInt32(store, address - 4);
    return Encoding.Unicode.GetString(memory.GetSpan(store).Slice(address, length));
}

using var engine = new Engine();
using var module = Module.FromFile(engine, "bucketing-lib-debug.wasm");
using var linker = new Linker(engine);
using var store = new Store(engine);

linker.DefineWasi();
linker.Define(
    "env",
    "abort",
    Function.FromCallback(store, (Caller caller, int messagePtr, int filenamePtr, int linenum, int colnum) =>
    {
        var memory = caller.GetMemory("memory");
        if (memory is null)
        {
            throw new InvalidOperationException();
        }

        var message = ReadAssemblyScriptString(caller, memory, messagePtr);
        var filename = ReadAssemblyScriptString(caller, memory, filenamePtr);

        throw new Exception($"abort: {message} ({filename}:{linenum}:{colnum})");
    })
);

const string CONFIG_JSON = "{\"project\":{\"_id\":\"_project\"},\"environment\":{\"_id\":\"environment\"}}";
const string USER_JSON = "{\"user_id\":\"test_id\"}";

var instance = linker.Instantiate(store, module);
var memory = instance.GetMemory(store, "memory");
if (memory is null)
{
    throw new InvalidOperationException();
}

var __new = instance.GetFunction(store, "__new")!;
if (__new is null)
{
    throw new InvalidOperationException();
}

var configAddress = (int) __new.Invoke(store, Encoding.Unicode.GetByteCount(CONFIG_JSON), 1)!;
var userAddress = (int) __new.Invoke(store, Encoding.Unicode.GetByteCount(USER_JSON), 1)!;

Encoding.Unicode.GetBytes(CONFIG_JSON, memory.GetSpan(store).Slice(configAddress));
Encoding.Unicode.GetBytes(USER_JSON, memory.GetSpan(store).Slice(userAddress));

var generateBucketedConfig = instance.GetFunction(store, "generateBucketedConfig")!;
if (generateBucketedConfig is null)
{
    throw new InvalidOperationException();
}

var result = generateBucketedConfig.Invoke(store, configAddress, userAddress);

Console.WriteLine("generateBucketedConfig result: " + result);
```

I get this from `dotnet run`:

```sh
$ dotnet run
Unhandled exception. Wasmtime.TrapException: abort: Project missing key (src/index.ts:51:13)
   at Wasmtime.Function.Invoke(StoreContext context, ReadOnlySpan`1 arguments)
   at Wasmtime.Function.Invoke(IStore store, Object[] arguments)
   at Program.<Main>$(String[] args) in /Users/phuene/tmp/foo/Program.cs:line 64
```

It appears it's marshaling the JSON correctly, just missing some data now.

**Comment by peterhuene** [comment]
By the way, with the above program's WASI configuration, you should be able to `console.log` from within the exported function in the `AssemblyScript` program to verify that it is indeed passing the JSON correctly.

**Comment by JamieSinn** [comment]
Awesome! Thanks!

We had issues enabling and finding the proper WASI config - it would always complain with not being able to find `fd_write`.

WASM is a new area for us - and this helps a ton in understanding how to use it!
